// Configuration client — demenageur-template
// Modifier les valeurs ci-dessous pour personnaliser le site

export const clientConfig = {
  NOM_ENTREPRISE: "Nom de l'Entreprise",
  NOM_LEGAL: "Nom de l'Entreprise SARL",
  SIRET: "000 000 000 00000",
  METIER: "transporteur",
  METIER_LABEL: "Transporteur",
  GENRE_DIRIGEANT: "M",
  PRENOM_DIRIGEANT: "Prénom",
  NOM_DIRIGEANT: "Nom",
  ANNEE_CREATION: "2010",
  ANNEES_EXPERIENCE: "15",
  TELEPHONE: "00 00 00 00 00",
  EMAIL: "contact@votre-domaine.fr",
  ADRESSE: "1 Rue de la Paix",
  CODE_POSTAL: "00000",
  VILLE: "Votre Ville",
  DEPARTEMENT: "Votre Département",
  REGION: "Votre Région",
  COMMUNE_1: "Commune Voisine 1",
  COMMUNE_2: "Commune Voisine 2",
  COMMUNE_3: "Commune Voisine 3",
  FONDATEUR_NOM: "Prénom Nom",
  PAYS: "France",
  HORAIRES: "Lun-Ven: 8h00-18h00",
  ZONE_INTERVENTION: "Votre ville et région",
  LATITUDE: "46.603354",
  LONGITUDE: "1.888334",
  DOMAINE: "www.votre-domaine.fr",
  META_TITLE: "Nom de l'Entreprise | Transporteur à Votre Ville",
  META_DESCRIPTION: "Transporteur à Votre Ville. Transport routier de fret, logistique, affrètement. Devis gratuit sous 2h.",
  META_KEYWORDS: "transporteur, transport routier, fret, logistique, affrètement, transport européen",
  SLOGAN: "Votre Slogan Ici",
  ACCROCHE_HERO: "Transport Routier — Votre Ville & Votre Région",
  DESCRIPTION_ENTREPRISE: "Votre description d'entreprise. Transport routier, logistique, affrètement — un service complet et sur mesure.",
  DESCRIPTION_FOOTER: "Votre description courte pour le footer du site.",
  DESCRIPTION_APROPOS: "Fondée par Prénom Nom, l'entreprise est née d'une passion pour le transport et la logistique.",
  GOOGLE_MAPS_URL: "",
  FACEBOOK_URL: "",
  INSTAGRAM_URL: "",
  LINKEDIN_URL: "",
  N8N_WEBHOOK: "",
  ADMIN_PASSWORD: "1234",
} as const;

export type ClientConfigKey = keyof typeof clientConfig;
