// Configuration client — demenageur-template
// Modifier les valeurs ci-dessous pour personnaliser le site

export const clientConfig = {
  NOM_ENTREPRISE: "DM Services",
  NOM_LEGAL: "DM Services",
  SIRET: "000 000 000 00000",
  METIER: "déménageur",
  METIER_LABEL: "Déménageur",
  GENRE_DIRIGEANT: "Mme",
  PRENOM_DIRIGEANT: "Magalie",
  NOM_DIRIGEANT: "Rouleau",
  ANNEE_CREATION: "2015",
  ANNEES_EXPERIENCE: "10",
  TELEPHONE: "06 21 33 80 56",
  EMAIL: "dmservices44@gmail.com",
  ADRESSE: "2 Rue de la Prévoyance",
  CODE_POSTAL: "69100",
  VILLE: "Villeurbanne",
  DEPARTEMENT: "Rhône",
  REGION: "Auvergne-Rhône-Alpes",
  COMMUNE_1: "Lyon",
  COMMUNE_2: "Caluire-et-Cuire",
  COMMUNE_3: "Vaulx-en-Velin",
  FONDATEUR_NOM: "Magalie Rouleau",
  PAYS: "France",
  HORAIRES: "Lun-Sam: 7h00-20h00",
  ZONE_INTERVENTION: "Villeurbanne, Lyon et agglomération lyonnaise",
  LATITUDE: "45.7676",
  LONGITUDE: "4.8844",
  DOMAINE: "www.dm-services.fr",
  META_TITLE: "DM Services | Déménagement à Villeurbanne & Lyon",
  META_DESCRIPTION: "DM Services, votre déménageur à Villeurbanne et Lyon. Déménagement particuliers et entreprises, garde-meuble, emballage. Devis gratuit.",
  META_KEYWORDS: "déménageur, déménagement, Villeurbanne, Lyon, garde-meuble, emballage, transport, déménagement entreprise",
  SLOGAN: "Votre déménagement en toute sérénité",
  ACCROCHE_HERO: "Déménagement — Villeurbanne, Lyon & Rhône-Alpes",
  DESCRIPTION_ENTREPRISE: "DM Services, votre partenaire déménagement à Villeurbanne et Lyon. Particuliers et professionnels, nous assurons un service complet : emballage, transport, montage et garde-meuble.",
  DESCRIPTION_FOOTER: "DM Services — Déménageur professionnel à Villeurbanne et Lyon. Devis gratuit, service soigné.",
  DESCRIPTION_APROPOS: "Fondée par Magalie Rouleau, DM Services est née d'une volonté d'offrir un service de déménagement humain, soigné et accessible à Villeurbanne et dans toute l'agglomération lyonnaise.",
  GOOGLE_MAPS_URL: "",
  FACEBOOK_URL: "",
  INSTAGRAM_URL: "",
  LINKEDIN_URL: "",
  N8N_WEBHOOK: "",
  ADMIN_PASSWORD: "1234",
} as const;

export type ClientConfigKey = keyof typeof clientConfig;
